repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: double-quote-string-fixer
    -   id: mixed-line-ending
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.7.1
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/psf/black
    rev: '22.1.0'
    hooks:
    -   id: black
        args:
            - "-S"
            - "-l"
            - "100"
            - "--force-exclude"
            - "types.py"


-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.931'
    hooks:
    -   id: mypy
        args:
            - "--disable-error-code"
            - "name-defined"
            - "--disable-error-code"
            - "no-redef"
            - "--strict"
            - "--allow-subclassing-any"
            - "--allow-untyped-decorators"
        exclude: "tests/*"
        additional_dependencies:
            - "black"
